### ISSUE TITLE
how use react-storybook-relay-container for nested components?

### ISSUE THREAD

**Issue by FilipMessa** [orta/react-storybooks-relay-container#8]
Hello,
Is there some approach how use this for the nested relay components?
I mean Component `ListItem` have a children Items `component` which are also a relay components. This react-storybooks-relay-container doesn't works, for children if they are also connect to relay.

**Comment by divyenduz** [comment]
+1

This fails for components using a connection with an error that looks like this. 

```
Cannot read property 'metadata' of undefined
TypeError: Cannot read property 'metadata' of undefined
    at findConnectionMetadata (http://localhost:6006/static/preview.bundle.js:62629:39)
    at createContainerWithFragments (http://localhost:6006/static/preview.bundle.js:62656:18)
    at http://localhost:6006/static/preview.bundle.js:63002:12
    at ContainerConstructor (http://localhost:6006/static/preview.bundle.js:49494:19)
    at http://localhost:6006/static/preview.bundle.js:41642:16
    at measureLifeCyclePerf (http://localhost:6006/static/preview.bundle.js:41412:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:6006/static/preview.bundle.js:41641:14)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:6006/static/preview.bundle.js:41616:21)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:6006/static/preview.bundle.js:41524:21)
    at Object.mountComponent (http://localhost:6006/static/preview.bundle.js:4549:35)
```

I will investigate this further later today and send a PR if I run into something. Thanks for putting this repository together :)

**Comment by kdawgwilk** [comment]
I am trying to work through this as well, any ideas for how to proceed?

**Comment by iMadooc** [comment]
I have the same problem :(

**Comment by Lpaydat** [comment]
I solved this issue, the problem is our `getFragment` function is do nothing.
So when relay use that function to map `fragments`, it got a bunch of `undefined` values 
(and it's tried to get `metadata` from those `undefined` which is shown on the error log).

**Comment by kdawgwilk** [comment]
@Lpaydat What was your solution?
